version: '3'

services:
	mysql: 
		image: mysql:latest
		environment: 
			- MYSQL_ROOT_PASSWORD=Vietnamnet.vn
			- MYSQL_USER=admin
			- MYSQL_PASSWORD=123456
			- MYSQL_DATABASE=identity_service
		volumes:
			- mysql-data/var/lib/mysql
			- ./identity_service.sql:/docker-entrypoint-initdb.d/init.sql
	web:
		image: spring-boot-identity-microservice:latest
		ports: 
			- "8005:8080"
		depends_on:
			- mysql
volumes:
	mysql-data: